# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- woelements

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '16.x'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build React App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(node_version)'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build the project'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          package.json
          build/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
      displayName: 'Copy necessary files'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
        replaceExistingArchive: true
      displayName: 'Archive build directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
        artifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy to Azure WebApp'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            displayName: 'Download Build Artifact'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'woelements'  # Update with the actual service connection name
              appType: 'webApp'
              WebAppName: 'woelements'
              packageForLinux: '$(Pipeline.Workspace)/drop/drop.zip'
              RuntimeStack: 'NODE|16-lts'
              DeploymentType: 'zipDeploy'
              TakeAppOfflineFlag: true
            displayName: 'Deploy to Azure Web App'
