# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- woelements

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '16.x'  # Update to a more recent version
  appservicedeploy_retrytimeout: 30

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the project'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'woelements'
    appType: 'webApp'
    WebAppName: 'woelements'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: 'NODE|16-lts'
    DeploymentType: 'zipDeploy'
    TakeAppOfflineFlag: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'logs'
    publishLocation: 'Container'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'pipeline-logs'
    publishLocation: 'pipeline'

