# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - woelements  # or your main branch name

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              version: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install and Build'

          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/package
              zip -r $(Build.ArtifactStagingDirectory)/package/app.zip .
            displayName: 'Package Application'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/package'
              ArtifactName: 'drop'
              publishLocation: 'Container'
