# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- woelements

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '16.x'
  appservicedeploy_retrytimeout: 30

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the project'

# Archive the build directory
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build directory'

# Publish the artifact so it can be used in the release pipeline
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'pipeline-logs'
    publishLocation: 'pipeline'

